export const GET_BOOKS_REQUEST = 'GET_BOOKS_REQUEST';
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const GET_BOOKS_ERROR = 'GET_BOOKS_ERROR';

export const GET_BOOK_REQUEST = 'GET_BOOK_REQUEST';
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export const GET_BOOK_ERROR = 'GET_BOOK_ERROR';

export const GET_AUTHORS_REQUEST = 'GET_AUTHORS_REQUEST';
export const GET_AUTHORS_SUCCESS = 'GET_AUTHORS_SUCCESS';
export const GET_AUTHORS_ERROR = 'GET_AUTHORS_ERROR';

export const GET_AUTHOR_REQUEST = 'GET_AUTHOR_REQUEST';
export const GET_AUTHOR_SUCCESS = 'GET_AUTHOR_SUCCESS';
export const GET_AUTHOR_ERROR = 'GET_AUTHOR_ERROR';

export const GET_AUTHOR_INFO_REQUEST = 'GET_AUTHOR_INFO_REQUEST';
export const GET_AUTHOR_INFO_SUCCESS = 'GET_AUTHOR_INFO_SUCCESS';
export const GET_AUTHOR_INFO_ERROR = 'GET_AUTHOR_INFO_ERROR';